steps:
  #step 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hackaton2019-242912/paynemtservice', '.']
  #step 2
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west4'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hackaton2019-gke-cluster'
images: ['gcr.io/hackaton2019-242912/paynemtservice']
tags: ['paynemtservice_cloud_build']
